name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Packages
        run: |
          yarn
      - name: Lint check
        run: |
          yarn lint
      - name: Test
        run: |
          yarn test
      - name: Deploy chromatic
        run: |
          yarn chromatic